### ISSUE TITLE
Alignment explanation

### ISSUE THREAD

**Issue by sagarsingari** [yetanalytics/datasim#41]
Hi there,
Can I get some clarification on Alignment.json. I need clarification specifically on the IRI part. For example, for the below Alignment:
{"mbox::mailto:bob@example.org":
  {"https://example.org/activity/a": 0.5,
   "https://example.org/activity/c": -0.2}
}
What "https://example.org/activity/a" means ? Is it supposed to be always written in this format or it depends on the profile? And what do /a, /c mean?

I understand that the weight defines the propensity but I don't understand how the IRI defines a part of profile(because I don't see how the IRI relates to elements in the profile)

Thanks!

**Comment by cliffcaseyyet** [comment]
Hi Sagar,

The alignments are used to weight the simulation towards or against a component of the xAPI Profile for a given Actor. The provided example is for a Profile that doesn't exist, so it's not intended to represent a real use case (perhaps we should redo that section of the docs to be clearer), but the format is as follows:

```
{
  "WAY TO IDENTIFY A USER": {
    "ID FROM THE PROFILE(S)" : 0.5,
    "ANOTHER ID FROM THE PROFILE(S)" : -0.2}
}
```

The IRI/ID is the unique ID of the specific part of the Profile you want to have an impact on. Usually this is going to be the ID of a Pattern, Activity, or StatementTemplate in the Profile itself.

So let's say you wanted to weight me against or for some CMI5 patterns, for example. You might use:

```
{
  "mbox::mailto:cliff@example.org" : {
    "https://w3id.org/xapi/cmi5#completedandpassed": -0.75,
    "https://w3id.org/xapi/cmi5#completedandmaybefailed": 0.75
  }
}
```

Now you will have made me much more likely to fail in a simulation using that Profile. Let me know if that makes sense.

Thanks,
-Cliff

**Comment by sagarsingari** [comment]
Thanks again, Cliff. This is very helpful. 
Just a couple of more queries.

Can IRI/ID be the ID of a Verb(i.e anything other than Pattern, Activity or StatementTemplate) ?

Also, on another note, I've seen that the simulation generates statements even if you provide incorrect Alignment data(or even if it's absent). All that it needs is the profile to be immaculate.

**Comment by cliffcaseyyet** [comment]
Hi Sagar,

You are correct that you can put just about anything into the ID keys of a (valid) alignments json structure and it will still generate. On intake/validation it does not validate that the alignments "will have an effect" if that makes sense, so they may be dead references and it will still run, it will just ignore them. 

One test I do for if my alignment had an impact is that since the simulation is deterministic it will always run the same way with the same inputs - and that extends to when you add bad alignment references which do NOT impact the generated data. Try generating an output set with and without your proposed alignments and then check if the generated data is identical with a hash or something. If the hash changes, you know you are doing something to the sim with your alignment. If not, your alignment is having no effect.

In regard to verbs, at this time DATASIM does not take verb alignment into account (this should be in docs, thanks for pointing it out!). The way we considered its usage was that since a statement template is 1-1 with a verb, you can have that level of granularity in influencing the generated data through template alignments. Is there a use case you are working on that requires verb alignment that won't be satisfied by statement template alignment? It would be helpful to know as something we can consider for future dev.

Thanks,
-Cliff

**Comment by sagarsingari** [comment]
No, as of now I don't have any use case that would require verb alignment. Just wanted to know what is the scope of a valid Alignment json.

Thanks for the clarification Cliff, I now have a better understanding of this.
